### ISSUE TITLE
Mark version with release section of github

### ISSUE THREAD

**Issue by xchwarze** [dzzie/SysAnalyzer#7]
Hi David! 
Since you made SysAnalyzer it is part of the different tool packs we make at Indetectables.
The latest version of this ([which is this one](https://github.com/indetectables-net/toolkit)) integrates an updater for all the tools and I would like to implement the auto update with your tool as well.
So I wanted to ask you if you could not use the releases section in this repo to be able to do it.
Thanks!

**Comment by dzzie** [comment]
Hi, here you go: https://github.com/dzzie/SysAnalyzer/releases/tag/v2.10.341

**Comment by dzzie** [comment]
I can look into one of the portable apps makers and see if they can work with it. It uses a bunch of libraries though so not sure how well that would go.I will also test it on some clean virtual machines and see if I can replicate the missing component error.It will be best to grab a copy from the main download link on sandsprite as I am updating it often right now. I think I did archive an installer in one of my other repos as a release for the flare vm guys but couldn’t find which one on a quick glance. Will update when I check on the missing dependency report and portable app test. Since it comes with several injection dlls I doubt the pcode debugger or remote scripting feature would work if portable.Sent from my iPhoneOn Feb 22, 2023, at 10:01 AM, DSR! ***@***.***> wrote:﻿
Thanks! it works perfectly!
 Universal Tool Updater v1.7.2 - by DSR!
 https://github.com/xchwarze/universal-tool-updater

SysAnalyzer: updated from 0 --> v2.10.341
SysAnalyzer: downloading update "v2.10.341.zip"
SysAnalyzer: 17.9MiB [00:01, 11.1MiB/s]
SysAnalyzer: saving to folder C:\code\toolkit\toolkit\Monitor\SysAnalyzer
SysAnalyzer: update complete

I take advantage of this contact to ask you this, I am working locally to add VBDEC and I had some doubts:

Is there any way to use it portable? I have the dependencies installed and I still get the typical error "Component '' or one of its dependencies not correctly registered"
Could you make a repo like this for that project so I can add it to the auto updater?

**Comment by dzzie** [comment]
what OS and service pack are you running where vbdec will not run properly? 
Do you have any antivirus installed? Does antivirus show any messages in its logs?

It will not run on an XP SP0, but from XP SP3 and up it should be fine. I just verified on XPSP3, Win7 and I develop on Windows 10.

**Comment by xchwarze** [comment]
hello!
I use W10 updated up to date, I was going to try it in a vm to see if the same error happened to me but I still couldn't free myself.

The steps I followed are these:
1) unpack the exe with innounp.exe to access the files and recreate the installation .iss code
2) I made a .bat to use regserver with cli
```
@ECHO OFF

echo Register program dlls
echo ----------------------------------------
echo .

1>nul 2>nul reg query HKU\S-1-5-19 || (
	echo You must run the command prompt as administrator to install.
	ping 127.0.0.1 > NUL 2>&1
    exit /b 1
)


cd "%~dp0"
regsvr32 /s richtx32.ocx
regsvr32 /s MSCOMCTL.OCX
regsvr32 /s msscript.ocx
regsvr32 /s TLBINF32.DLL
regsvr32 /s scivb2.ocx
```

It should work as if it were installed... but it doesn't.
Maybe the problem is that I'm not copying them to System32...

**Comment by dzzie** [comment]
here are all the registrations and file locations I use, all of the ones with the  regserver flag must be
registered with regsvr32. Make sure to run rungsvr32 as admin, and it is also critical that you run the
32bit version of regsvr32 from the SysWOW64 directory. 

There is a 64 bit version of regsvr32 which will register components as if they were 64bit ActiveX controls
I never understood why they didnt rename it but it is what it is.

```
Source: dependancies\MSCOMCTL.OCX; DestDir: {sys}; Flags: regserver uninsneveruninstall
Source: dependancies\msscript.ocx; DestDir: {sys}; Flags: regserver uninsneveruninstall
Source: dependancies\richtx32.ocx; DestDir: {sys}; Flags: regserver uninsneveruninstall
Source: dependancies\TLBINF32.DLL; DestDir: {sys}; Flags: regserver uninsneveruninstall
Source: dependancies\scivb2.ocx; DestDir: {app}; Flags: regserver ignoreversion
Source: dependancies\java.hilighter; DestDir: {app};
Source: dependancies\SciLexer.dll; DestDir: {app}
Source: dependancies\hexed.ocx; DestDir: {app}; Flags: regserver ignoreversion
Source: dependancies\IDAClientLib2.dll; DestDir: {app}; Flags: regserver ignoreversion
Source: dependancies\decLib.dll; DestDir: {app}; Flags: regserver ignoreversion
Source: dependancies\IDASrvr2.dll; DestDir: {app}
Source: dependancies\libdasm.dll; DestDir: {app}
Source: dependancies\zlib.dll; DestDir: {app}
Source: dependancies\procLib2.dll; DestDir: {app}; Flags: regserver ignoreversion
Source: dependancies\spSubclass.dll; DestDir: {app}; Flags: regserver ignoreversion
Source: dependancies\UTypes.dll; DestDir: {app}; Flags: ignoreversion

Source: blank.mdb; DestDir: {app}
Source: vbdec.exe; DestDir: {app}
Source: target.runtime; DestDir: {app}
Source: openscript.dll; DestDir: {app}
Source: tlbViewer.exe; DestDir: {app}
Source: pcodeDBG.dll; DestDir: {app}
;Source: MSVBVM50.EXP; DestDir: {app}
Source: clsid.mdb; DestDir: {app}
Source: data\VB32.OLB; DestDir: {app}\data\;    Flags: regtypelib
Source: data\vb5.imports; DestDir: {app}\data\
Source: data\vb6.imports; DestDir: {app}\data\
Source: data\VB6.OLB; DestDir: {app}\data\;     Flags: regtypelib
Source: data\vbrt_ords.backup.txt; DestDir: {app}\data\
Source: intellisense\CActXLib.txt; DestDir: {app}\intellisense\
Source: intellisense\CActXRef.txt; DestDir: {app}\intellisense\
Source: intellisense\cb.txt; DestDir: {app}\intellisense\
Source: intellisense\cco.txt; DestDir: {app}\intellisense\
Source: intellisense\CControl.txt; DestDir: {app}\intellisense\
Source: intellisense\cex.txt; DestDir: {app}\intellisense\
Source: intellisense\CMember.txt; DestDir: {app}\intellisense\
Source: intellisense\CMethodLink.txt; DestDir: {app}\intellisense\
Source: intellisense\CObjectInfo.txt; DestDir: {app}\intellisense\
Source: intellisense\CObjectTable.txt; DestDir: {app}\intellisense\
Source: intellisense\COcxItem.txt; DestDir: {app}\intellisense\
Source: intellisense\col.txt; DestDir: {app}\intellisense\
Source: intellisense\COptObjInfo.txt; DestDir: {app}\intellisense\
Source: intellisense\CProjectInfo.txt; DestDir: {app}\intellisense\
Source: intellisense\CProjectInfo2.txt; DestDir: {app}\intellisense\
Source: intellisense\CPStrRef.txt; DestDir: {app}\intellisense\
Source: intellisense\CPStrRef2.txt; DestDir: {app}\intellisense\
Source: intellisense\CVBHeader.txt; DestDir: {app}\intellisense\
Source: intellisense\dlg.txt; DestDir: {app}\intellisense\
Source: intellisense\frm.txt; DestDir: {app}\intellisense\
Source: intellisense\fso.txt; DestDir: {app}\intellisense\
Source: intellisense\tb.txt; DestDir: {app}\intellisense\
Source: intellisense\vbp.txt; DestDir: {app}\intellisense\
Source: intellisense\cmd.txt; DestDir: {app}\intellisense\
Source: intellisense\cn.txt; DestDir: {app}\intellisense\
Source: intellisense\rs.txt; DestDir: {app}\intellisense\
Source: intellisense\app.txt; DestDir: {app}\intellisense\
Source: intellisense\CImport.txt; DestDir: {app}\intellisense\
Source: intellisense\CExport.txt; DestDir: {app}\intellisense\
Source: intellisense\remote.txt; DestDir: {app}\intellisense\
Source: intellisense\CConstPoolEntry.txt; DestDir: {app}\intellisense\
Source: intellisense\ProgressBar.txt; DestDir: {app}\intellisense\
Source: scripts\help.txt; DestDir: {app}\scripts\
Source: scripts\prompt_hex_conv.txt; DestDir: {app}\scripts\
Source: scripts\str_refs.txt; DestDir: {app}\scripts\
Source: scripts\walk_methods.txt; DestDir: {app}\scripts\
Source: scripts\ado_query.txt; DestDir: {app}\scripts\
Source: scripts\dump_declares.txt; DestDir: {app}\scripts\
Source: scripts\dump_actx.txt; DestDir: {app}\scripts\
Source: scripts\dump_optional_vals.txt; DestDir: {app}\scripts\
Source: scripts\vbs_remote_example.vbs; DestDir: {app}\scripts\
Source: scripts\python_remote_example.py; DestDir: {app}\scripts\
Source: scripts\db_automation.js; DestDir: {app}\scripts\
Source: scripts\gui.txt; DestDir: {app}\scripts\
Source: scripts\gui_scan.js; DestDir: {app}\scripts\
Source: scripts\gui_controls_and_props.txt; DestDir: {app}\scripts\
Source: scripts\search_structs.txt; DestDir: {app}\scripts\
Source: scripts\remoteObj.txt; DestDir: {app}\scripts\
Source: scripts\remote.typName.txt; DestDir: {app}\scripts\
Source: scripts\resolveConstPool.txt; DestDir: {app}\scripts\
Source: scripts\remoteInstances.txt; DestDir: {app}\scripts\
Source: scripts\extractBuf.txt; DestDir: {app}\scripts\
```

**Comment by xchwarze** [comment]
Of course that was the problem, I was not registering the components that were outside of {sys}. I just didn't see them. 
Since the license does not allow redistribution, my local tests are concluded.
Anyway, could you make them a repo to upload the updates so I can automate the updates of it?

**Comment by dzzie** [comment]
I would appreciate if all downloads just went through the main download link. 

http://sandsprite.com/vbdec/download.php?edition=full

This will ensure you always get the current version. I thought about a git repo to archive installers but it is to much work to keep it up to date when it is under active development.

**Comment by xchwarze** [comment]
When you upload the VBDEC_Setup.exe to the server, could you upload a changelog.txt?
So I could check the contents of the file and use it to run a regex that gives me the latest version number.

**Comment by dzzie** [comment]
Im not really that organized, vb6 doesnt really have post build commands to allow for automation like version export to file and setup compilation and upload is a manual process. All of the data in the innosetup is compressed, so I wont be able to auto extract version from that on the server side. Maybe I could manually upload a copy of the exe along with the installer everytime and have a web script that extracts version info from that..but thats a 2mb parse everytime. 

I will think if there is a reasonable automated way with minimal manual labor. Does your tool run on a users system and alert them that a new version is available? Otherwise just always having access to the latest at a stable link seems like enough for most things?

**Comment by xchwarze** [comment]
It is that to do that I need to be able to determine which is the last version, in the case of Process Explorer for example I use the string of the title for that.
In others I get them from the changelog they have uploaded or from the latest release if they use github.
Just in the case of VBDEC I have nothing to compare against.

**Comment by dzzie** [comment]
Ok I will look, I think I can have my ide addin generate a version.txt on compilation then just manually upload that along with the setup every time 

Sent from my iPhone

**Comment by dzzie** [comment]
ok I modified one of my addins to generate a version file every time I compile it. I will try to remember to upload the version file every time I update the installer, but it will be a manual process. Since the file generation is on exe compilation, and not on setup compilation, I can not currently include the hash of the installer without further changes to my build process. The static file path will be:

http://sandsprite.com/vbdec/vbdec_version.txt

Format is

```
1.0.0.921
2/23/2023 9:47:47 PM
vbdec.exe: [sha256]
```

**Comment by dzzie** [comment]
One other thought, will the version file be checked by every single client on what kind of interval or just by some server side code intermittently? 

I used to have a rss feed on my blogs but had to take it down as people were hammering it horribly. I’m not even sure I really want my updates to be trackable.

**Comment by dzzie** [comment]
I have thought about this and I do not want to support the version querying.

- extra steps to keep in sync
- server hammering by lots of people
- when I find work again I will be under employment agreement and not really allowed to work on it anymore and I don’t want to leave an explicit log of updates and times that would be easy to track and could cost me
- this is just a hobby project I give away I don’t care to add any additional labor costs or frustrations

**Comment by xchwarze** [comment]
Any hosting should be able to handle the load of having a txt request from time to time. There are also not that many that have labs for malware/reverse analysis, so the updater I am maintaining is not that heavily used either.
So it should never cause an excess load on a server.

Anyway, if you don't want to implement that no problem.
Thanks for the help in tracking the SysAnalizer updates.

**Comment by dzzie** [comment]
yeah I just dont want to advertise version or let history be tracked easily
